name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set JDK17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      # 关键：删除文件头部BOM隐形字符、全角空格
      - name: Remove BOM & illegal char
        run: |
          sed -i 's/\xEF\xBB\xBF//' app/build.gradle
          sed -i '1s/^[ \t]*//' app/build.gradle

      - name: Build Debug APK
        run: gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Clean invalid BOM & blank
        run: |
          sed -i '1s/^\xEF\xBB\xBF//' app/build.gradle
          sed -i '1s/^[[:space:]]*//' app/build.gradle
      - name: Build APK
        run: gradle assembleDebug
